version: '3'
services:
  webapp:
    build:
      context: ./
      args:
        PORT: $PORT
    image: speechtree:$RELEASE
    container_name: speechtree
    restart: always
    ports:
      - "$PORT"
    env_file: .env
    environment:
      - VIRTUAL_HOST=speechtree.com,www.speechtree.com,earlyrain.org,www.earlyrain.org,speechtree-local.com

networks:
  default:
    external:
      name: nginx-proxy
